### ISSUE TITLE
Building error in debian testing

### ISSUE THREAD

**Issue by remenor** [beandog/dvd_info#2]
Two error messages are obtained when trying to build in Debian testing

`make  all-am
make[1]: se entra en el directorio '/home/diego1/Descargas/Programas linux/dvd_info-1.10'
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_info.o -MD -MP -MF .deps/dvd_info-dvd_info.Tpo -c -o dvd_info-dvd_info.o `test -f 'dvd_info.c' || echo './'`dvd_info.c
mv -f .deps/dvd_info-dvd_info.Tpo .deps/dvd_info-dvd_info.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_open.o -MD -MP -MF .deps/dvd_info-dvd_open.Tpo -c -o dvd_info-dvd_open.o `test -f 'dvd_open.c' || echo './'`dvd_open.c
mv -f .deps/dvd_info-dvd_open.Tpo .deps/dvd_info-dvd_open.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_drive.o -MD -MP -MF .deps/dvd_info-dvd_drive.Tpo -c -o dvd_info-dvd_drive.o `test -f 'dvd_drive.c' || echo './'`dvd_drive.c
mv -f .deps/dvd_info-dvd_drive.Tpo .deps/dvd_info-dvd_drive.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_device.o -MD -MP -MF .deps/dvd_info-dvd_device.Tpo -c -o dvd_info-dvd_device.o `test -f 'dvd_device.c' || echo './'`dvd_device.c
mv -f .deps/dvd_info-dvd_device.Tpo .deps/dvd_info-dvd_device.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_vmg_ifo.o -MD -MP -MF .deps/dvd_info-dvd_vmg_ifo.Tpo -c -o dvd_info-dvd_vmg_ifo.o `test -f 'dvd_vmg_ifo.c' || echo './'`dvd_vmg_ifo.c
mv -f .deps/dvd_info-dvd_vmg_ifo.Tpo .deps/dvd_info-dvd_vmg_ifo.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_track.o -MD -MP -MF .deps/dvd_info-dvd_track.Tpo -c -o dvd_info-dvd_track.o `test -f 'dvd_track.c' || echo './'`dvd_track.c
mv -f .deps/dvd_info-dvd_track.Tpo .deps/dvd_info-dvd_track.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_cell.o -MD -MP -MF .deps/dvd_info-dvd_cell.Tpo -c -o dvd_info-dvd_cell.o `test -f 'dvd_cell.c' || echo './'`dvd_cell.c
mv -f .deps/dvd_info-dvd_cell.Tpo .deps/dvd_info-dvd_cell.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_vts.o -MD -MP -MF .deps/dvd_info-dvd_vts.Tpo -c -o dvd_info-dvd_vts.o `test -f 'dvd_vts.c' || echo './'`dvd_vts.c
mv -f .deps/dvd_info-dvd_vts.Tpo .deps/dvd_info-dvd_vts.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_video.o -MD -MP -MF .deps/dvd_info-dvd_video.Tpo -c -o dvd_info-dvd_video.o `test -f 'dvd_video.c' || echo './'`dvd_video.c
mv -f .deps/dvd_info-dvd_video.Tpo .deps/dvd_info-dvd_video.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_audio.o -MD -MP -MF .deps/dvd_info-dvd_audio.Tpo -c -o dvd_info-dvd_audio.o `test -f 'dvd_audio.c' || echo './'`dvd_audio.c
mv -f .deps/dvd_info-dvd_audio.Tpo .deps/dvd_info-dvd_audio.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_subtitles.o -MD -MP -MF .deps/dvd_info-dvd_subtitles.Tpo -c -o dvd_info-dvd_subtitles.o `test -f 'dvd_subtitles.c' || echo './'`dvd_subtitles.c
mv -f .deps/dvd_info-dvd_subtitles.Tpo .deps/dvd_info-dvd_subtitles.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_time.o -MD -MP -MF .deps/dvd_info-dvd_time.Tpo -c -o dvd_info-dvd_time.o `test -f 'dvd_time.c' || echo './'`dvd_time.c
mv -f .deps/dvd_info-dvd_time.Tpo .deps/dvd_info-dvd_time.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_json.o -MD -MP -MF .deps/dvd_info-dvd_json.Tpo -c -o dvd_info-dvd_json.o `test -f 'dvd_json.c' || echo './'`dvd_json.c
mv -f .deps/dvd_info-dvd_json.Tpo .deps/dvd_info-dvd_json.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_chapter.o -MD -MP -MF .deps/dvd_info-dvd_chapter.Tpo -c -o dvd_info-dvd_chapter.o `test -f 'dvd_chapter.c' || echo './'`dvd_chapter.c
mv -f .deps/dvd_info-dvd_chapter.Tpo .deps/dvd_info-dvd_chapter.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_xchap.o -MD -MP -MF .deps/dvd_info-dvd_xchap.Tpo -c -o dvd_info-dvd_xchap.o `test -f 'dvd_xchap.c' || echo './'`dvd_xchap.c
mv -f .deps/dvd_info-dvd_xchap.Tpo .deps/dvd_info-dvd_xchap.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_info-dvd_init.o -MD -MP -MF .deps/dvd_info-dvd_init.Tpo -c -o dvd_info-dvd_init.o `test -f 'dvd_init.c' || echo './'`dvd_init.c
mv -f .deps/dvd_info-dvd_init.Tpo .deps/dvd_info-dvd_init.Po
gcc  -g -O2   -o dvd_info dvd_info-dvd_info.o dvd_info-dvd_open.o dvd_info-dvd_drive.o dvd_info-dvd_device.o dvd_info-dvd_vmg_ifo.o dvd_info-dvd_track.o dvd_info-dvd_cell.o dvd_info-dvd_vts.o dvd_info-dvd_video.o dvd_info-dvd_audio.o dvd_info-dvd_subtitles.o dvd_info-dvd_time.o dvd_info-dvd_json.o dvd_info-dvd_chapter.o dvd_info-dvd_xchap.o dvd_info-dvd_init.o -lm -ldvdread 
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_copy.o -MD -MP -MF .deps/dvd_copy-dvd_copy.Tpo -c -o dvd_copy-dvd_copy.o `test -f 'dvd_copy.c' || echo './'`dvd_copy.c
mv -f .deps/dvd_copy-dvd_copy.Tpo .deps/dvd_copy-dvd_copy.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_drive.o -MD -MP -MF .deps/dvd_copy-dvd_drive.Tpo -c -o dvd_copy-dvd_drive.o `test -f 'dvd_drive.c' || echo './'`dvd_drive.c
mv -f .deps/dvd_copy-dvd_drive.Tpo .deps/dvd_copy-dvd_drive.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_device.o -MD -MP -MF .deps/dvd_copy-dvd_device.Tpo -c -o dvd_copy-dvd_device.o `test -f 'dvd_device.c' || echo './'`dvd_device.c
mv -f .deps/dvd_copy-dvd_device.Tpo .deps/dvd_copy-dvd_device.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_open.o -MD -MP -MF .deps/dvd_copy-dvd_open.Tpo -c -o dvd_copy-dvd_open.o `test -f 'dvd_open.c' || echo './'`dvd_open.c
mv -f .deps/dvd_copy-dvd_open.Tpo .deps/dvd_copy-dvd_open.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_vmg_ifo.o -MD -MP -MF .deps/dvd_copy-dvd_vmg_ifo.Tpo -c -o dvd_copy-dvd_vmg_ifo.o `test -f 'dvd_vmg_ifo.c' || echo './'`dvd_vmg_ifo.c
mv -f .deps/dvd_copy-dvd_vmg_ifo.Tpo .deps/dvd_copy-dvd_vmg_ifo.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_track.o -MD -MP -MF .deps/dvd_copy-dvd_track.Tpo -c -o dvd_copy-dvd_track.o `test -f 'dvd_track.c' || echo './'`dvd_track.c
mv -f .deps/dvd_copy-dvd_track.Tpo .deps/dvd_copy-dvd_track.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_cell.o -MD -MP -MF .deps/dvd_copy-dvd_cell.Tpo -c -o dvd_copy-dvd_cell.o `test -f 'dvd_cell.c' || echo './'`dvd_cell.c
mv -f .deps/dvd_copy-dvd_cell.Tpo .deps/dvd_copy-dvd_cell.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_vts.o -MD -MP -MF .deps/dvd_copy-dvd_vts.Tpo -c -o dvd_copy-dvd_vts.o `test -f 'dvd_vts.c' || echo './'`dvd_vts.c
mv -f .deps/dvd_copy-dvd_vts.Tpo .deps/dvd_copy-dvd_vts.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_vob.o -MD -MP -MF .deps/dvd_copy-dvd_vob.Tpo -c -o dvd_copy-dvd_vob.o `test -f 'dvd_vob.c' || echo './'`dvd_vob.c
mv -f .deps/dvd_copy-dvd_vob.Tpo .deps/dvd_copy-dvd_vob.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_audio.o -MD -MP -MF .deps/dvd_copy-dvd_audio.Tpo -c -o dvd_copy-dvd_audio.o `test -f 'dvd_audio.c' || echo './'`dvd_audio.c
mv -f .deps/dvd_copy-dvd_audio.Tpo .deps/dvd_copy-dvd_audio.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_subtitles.o -MD -MP -MF .deps/dvd_copy-dvd_subtitles.Tpo -c -o dvd_copy-dvd_subtitles.o `test -f 'dvd_subtitles.c' || echo './'`dvd_subtitles.c
mv -f .deps/dvd_copy-dvd_subtitles.Tpo .deps/dvd_copy-dvd_subtitles.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_time.o -MD -MP -MF .deps/dvd_copy-dvd_time.Tpo -c -o dvd_copy-dvd_time.o `test -f 'dvd_time.c' || echo './'`dvd_time.c
mv -f .deps/dvd_copy-dvd_time.Tpo .deps/dvd_copy-dvd_time.Po
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_copy-dvd_chapter.o -MD -MP -MF .deps/dvd_copy-dvd_chapter.Tpo -c -o dvd_copy-dvd_chapter.o `test -f 'dvd_chapter.c' || echo './'`dvd_chapter.c
mv -f .deps/dvd_copy-dvd_chapter.Tpo .deps/dvd_copy-dvd_chapter.Po
gcc  -g -O2   -o dvd_copy dvd_copy-dvd_copy.o dvd_copy-dvd_drive.o dvd_copy-dvd_device.o dvd_copy-dvd_open.o dvd_copy-dvd_vmg_ifo.o dvd_copy-dvd_track.o dvd_copy-dvd_cell.o dvd_copy-dvd_vts.o dvd_copy-dvd_vob.o dvd_copy-dvd_audio.o dvd_copy-dvd_subtitles.o dvd_copy-dvd_time.o dvd_copy-dvd_chapter.o -lm -ldvdread 
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT dvd_backup-dvd_backup.o -MD -MP -MF .deps/dvd_backup-dvd_backup.Tpo -c -o dvd_backup-dvd_backup.o `test -f 'dvd_backup.c' || echo './'`dvd_backup.c
dvd_backup.c: In function ‘main’:
dvd_backup.c:266:19: error: ‘ifo_handle_t’ {aka ‘struct <anonymous>’} has no member named ‘file’
  266 |    DVDFileSeek(ifo->file, 0);
      |                   ^~
dvd_backup.c:296:39: error: ‘ifo_handle_t’ {aka ‘struct <anonymous>’} has no member named ‘file’
  296 |      ifo_bytes_read = DVDReadBytes(ifo->file, ifo_buffer, DVD_VIDEO_LB_LEN);
      |                                       ^~
make[1]: *** [Makefile:727: dvd_backup-dvd_backup.o] Error 1
make[1]: se sale del directorio '/home/diego1/Descargas/Programas linux/dvd_info-1.10'
make: *** [Makefile:513: all] Error 2
`

Sorry for my english

**Comment by beandog** [comment]
What version of libdvdread do you have installed?

**Comment by remenor** [comment]
libdvdread8 (version 6.1.1-2)

**Comment by beandog** [comment]
k looks like 6.1.1 made some changes to how it accesses an internal IFO. I figured out a fix, but I need to run lots of backup tests before I push it live. In the meantime, if you use 6.0 libdvdread it'll be fine.

**Comment by beandog** [comment]
k fixed
