### ISSUE TITLE
Compiling on Ubuntu 18.04 fails because automake 1.16 is not available

### ISSUE THREAD

**Issue by delthas** [beandog/dvd_info#7]
Hi,

Just opening this issue for anyone that needs to compile this on Ubuntu 18.04.

Compiling dvd_info requires automake 1.16, which is not available on Ubuntu 18.04 / Bionic. To compile successfully, I had to check out e42f1ddd8e3f6645ce5a6620b03ec474945da27f, which uses automake 1.15.

This can be closed right away.

**Comment by beandog** [comment]
@delthas thanks for posting that. If the user has dev autotools installed, they can run "autoreconf -fi" and then run ./configure like normally as well. :) But yeah autotools is a pain.
